name: Firedrake

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    container:
      image: docker://firedrakeproject/firedrake-vanilla:latest
      options: --user root

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Python info
        shell: bash -l {0}
        run: |
          source /home/firedrake/firedrake/bin/activate
          which python
          python -c "import sys; print('\n'.join(sys.path))"
          python -c "from firedrake import *"

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          source /home/firedrake/firedrake/bin/activate
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install pytest-cov
          python -m pip install pytest-check
          python -m pip install coveralls
          python -m pip install git+https://github.com/dolfin-adjoint/pyadjoint.git@master
          python -m pip install fdm

      - name: Install current package
        shell: bash -l {0}
        run: |
          source /home/firedrake/firedrake/bin/activate
          python -m pip install -e .

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          source /home/firedrake/firedrake/bin/activate
          python -c "import sys; print('\n'.join(sys.path))"
          python -m pytest --cov=fecr --cov-config=tests/.coveragerc tests/firedrake_backend -vvv

      - name: Send coveralls
        shell: bash -l {0}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          source /home/firedrake/firedrake/bin/activate
          coveralls

      - name: Send codecov
        shell: bash -l {0}
        run: |
          source /home/firedrake/firedrake/bin/activate
          bash <(curl -s https://codecov.io/bash)
